---
# playbook for setting up a development mac
- hosts: unix
  gather_facts: yes
  vars_files:
    - config.yml
  roles:
    - rounakdatta.dotfiles
    - setup
    - { role: geerlingguy.mas, when: ansible_distribution == "MacOSX" }
