---
# applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

homebrew_taps:
  spacemacs:
    tap_repo: "d12frosted/emacs-plus"
  passExtensions:
    tap_repo: "simplydanny/pass-extensions"
  openjdk:
    tap_repo: "adoptopenjdk/openjdk"

homebrew_applications:
  - git
  - tree
  - curl
  - wget
  - vim
  - go
  - pass
  - pass-update
  - gnupg
  - gnuplot
  - weechat
  - tmux
  - scala
  - fish
  - mysql
  - jq
  - gradle
  - pinentry
  - pinentry-mac
  - node
  - ruby
  - sbt
  - emacs-plus
  - shellcheck
  - forticlient

homebrew_cask_applications:
  - adoptopenjdk8
  - google-chrome
  - firefox
  - microsoft-edge
  - brave-browser
  - kitty
  - visual-studio-code
  - intellij-idea-ce
  - zoomus
  - notion
  - whatsapp
  - android-studio
  - telegram
  - mathpix-snipping-tool
  - vlc
  - postman
  - arduino
  - sublime-text
  - gopass-ui
  - qutebrowser
  - docker
  - keka
  - spotify
  - lyricsx
  - krita
  - hex-fiend
  - send-to-kindle
  - anki

external_applications_dmg:
  utorrent:
    name: uTorrentWeb
    url: https://utweb-assets.bittorrent.com/installer/uTorrentWeb.dmg

external_applications_pkg: {}

mas_installed_apps:
  - { id: 497799835, name: "Xcode (11.7)" }
  - { id: 490461369, name: "Bandwidth+ (1.18)" }
  - { id: 1254743014, name: "LyricsX (1.5.4)" }
  - { id: 1476177064, name: "Reading Queue (1.2.1)" }
  - { id: 1514817810, name: "Poolside FM (1.1.2)" }