---
# applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

homebrewbrew_taps:
  spacemacs:
    tap_repo: "d12frosted/emacs-plus"
  passExtensions:
    tap_repo: "simplydanny/pass-extensions"

applications:
  - git
  - tree
  - curl
  - wget
  - vim
  - go
  - pass
  - pass-update
  - gnupg
  - gnuplot
  - weechat
  - tmux
  - scala
  - openjdk
  - fish
  - mysql
  - jq
  - gradle
  - pinentry
  - pinentry-mac
  - node
  - ruby
  - spellcheck
  - sbt
  - emacs-plus

cask_applications:
  - google-chrome
  - firefox
  - microsoft-edge
  - brave-browser
  - kitty
  - visual-studio-code
  - intellij-idea-ce
  - zoomus
  - notion
  - whatsapp
  - android-studio
  - telegram
  - mathpix-snipping-tool
  - vlc
  - postman
  - arduino
  - sublime-text
  - gopass-ui
  - qutebrowser
  - docker
  - keka
  - spotify
  - lyricsx
  - krita
  - hex-fiend

external_applications_dmg:
  utorrent:
    name: uTorrentWeb
    url: https://utweb-assets.bittorrent.com/installer/uTorrentWeb.dmg

external_applications_pkg:
  sendToKindle:
    name: SendToKindleForMac-installer
    url: https://s3.amazonaws.com/sendtokindle/SendToKindleForMac-installer.pkg

mac_app_store_applications:
  xcode:
    id: 497799835
    name: "Xcode (11.7)"
  bandwidthPlus:
    id: 490461369
    name: "Bandwidth+ (1.18)"
  lyricsx:
    id: 1254743014
    name: "LyricsX (1.5.4)"
  readingQueue:
    id: 1476177064
    name: "Reading Queue (1.2.1)"
  poolSideFm:
    id: 1514817810
    name: "Poolside FM (1.1.2)"