---
# applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

homebrew_taps:
  emacs:
    tap_repo: "d12frosted/emacs-plus"
  passExtensions:
    tap_repo: "simplydanny/pass-extensions"
  openjdk:
    tap_repo: "AdoptOpenJDK/openjdk"

homebrew_applications:
  - git
  - tree
  - curl
  - wget
  - vim
  - go
  - pass
  - pass-update
  - gopass
  - gnuplot
  - weechat
  - tmux
  - scala
  - fish
  - mysql
  - jq
  - gradle
  - pinentry
  - pinentry-mac
  - node
  - ruby
  - sbt
  - emacs-plus
  - shellcheck
  - ripgrep
  - gnu-getopt
  - coreutils
  - nginx
  - telnet
  - redis
  - mysql
  - rclone
  - hugo

homebrew_cask_applications:
  - adoptopenjdk8
  - google-chrome
  - firefox
  - microsoft-edge
  - brave-browser
  - kitty
  - visual-studio-code
  - intellij-idea-ce
  - pycharm-ce
  - zoomus
  - notion
  - whatsapp
  - android-studio
  - telegram
  - mathpix-snipping-tool
  - vlc
  - postman
  - arduino
  - sublime-text
  - qutebrowser
  - docker
  - keka
  - spotify
  - lyricsx
  - krita
  - hex-fiend
  - send-to-kindle
  - anki
  - forticlient
  - microsoft-office
  - background-music
  - discord
  - goland
  - chromium
  - android-platform-tools
  - scroll-reverser
  - calibre

external_applications_dmg:
  utorrent:
    name: uTorrentWeb
    url: https://utweb-assets.bittorrent.com/installer/uTorrentWeb.dmg
  unetbootin:
    name: unetbootin
    url: https://github.com/unetbootin/unetbootin/releases/download/700/unetbootin-mac-700.dmg
  karabiner_elements:
    name: karabiner
    url: https://github.com/pqrs-org/Karabiner-Elements/releases/download/v13.1.0/Karabiner-Elements-13.1.0.dmg
  gpgtools:
    name: gpgtools
    url: https://releases.gpgtools.org/GPG_Suite-2020.2.dmg

external_applications_pkg:
  macports:
    name: macports
    url: https://distfiles.macports.org/MacPorts/MacPorts-2.6.4-10.15-Catalina.pkg

pip_python_packages:
  buku:
    name: buku
  buku_server:
    name: buku[server]
  airflow:
    name: apache-airflow[celery]
  airflow-livy-operators:
    name: airflow-livy-operators
  pyhive:
    name: pyhive
  pyspark:
    name: pyspark
  pykafka:
    name: pykafka
  boto3:
    name: boto3
  pandas:
    name: pandas
  numpy:
    name: numpy

mas_installed_apps:
  - { id: 497799835, name: "Xcode (11.7)" }
  - { id: 490461369, name: "Bandwidth+ (1.18)" }
  - { id: 1254743014, name: "LyricsX (1.5.4)" }
  - { id: 1476177064, name: "Reading Queue (1.2.1)" }
  - { id: 1514817810, name: "Poolside FM (1.1.2)" }
