---
# links the already-installed emacs on macOS
- name: links emacs to macOS Applications directory
  shell: "ln -Fs /opt/homebrew/opt/emacs-plus@28/Emacs.app /Applications"
  when: ansible_distribution == "MacOSX"

# sets up doom emacs
- name: checks if ~/.emacs.d is already present
  stat: path=~/.emacs.d
  register: emacsroot

- name: checks out from git
  command: git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
  when: emacsroot.stat.exists == False

- name: installs doom emacs
  shell: "yes | ~/.emacs.d/bin/doom install"
  when: emacsroot.stat.exists == False
