---
# sets up doom emacs
- name: checks if ~/.emacs.d is already present
  stat: path=~/.emacs.d
  register: emacsroot

- name: checks out from git
  command: git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
  when: emacsroot.stat.exists == False

- name: installs doom emacs
  command: ~/.emacs.d/bin/doom -y install
  when: emacsroot.stat.exists == False
