---
# setup homebrew and open the taps
- name: install homebrew
  shell: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"'
  args:
    creates: /usr/local/bin/brew

- name: ensure homebrew is updated
  homebrew:
    state: latest
    update_homebrew: yes

- name: opening the taps
  homebrew_tap:
    tap: "{{ item.value.tap_repo }}"
    state: present
  with_dict: "{{ homebrew_taps }}"