---
# install and update homebrew and cask -> open some taps
- name: install homebrew
  shell: 'yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  args:
    creates: /usr/local/bin/brew

- name: ensure homebrew is updated
  homebrew:
    state: latest
    update_homebrew: yes

- name: tap homebrew simplydanny/pass-extensions
  homebrew_tap:
    tap: "simplydanny/pass-extensions"
    state: present

- name: tap homebrew d12frosted/emacs-plus
  homebrew_tap:
    tap: "d12frosted/emacs-plus"
    state: present