---
- name: github setup
  include: ssh.yml
  vars:
    HostLabel: github.com
    Preferredauthentications: "publickey"
    StrictHostKeyChecking: "no"
    User: "rounakdatta"
    IdentityFile: "~/.ssh/keys/personal.pem"

- name: gitlab setup
  include: ssh.yml
  vars:
    HostLabel: gitlab.com
    Preferredauthentications: "publickey"
    StrictHostKeyChecking: "no"
    User: "rounakdatta"
    IdentityFile: "~/.ssh/keys/personal.pem"

# main tree
- name: application installation
  include: apps.yml

# manual installs
- name: emacs installation
  include: emacs.yml
