---
- name: configure and set up gnupg and password-store
  ignore_errors: "{{ ansible_check_mode }}"
  vars:
    public_key: ~/.secrets/public.key
    private_key: ~/.secrets/private.key
    pass_repository: git@gitlab.com:rounakdatta/pass.git
  block:
    - name: set correct permissions for SSH private key
      file:
        path: ~/.ssh/keys/personal.pem
        mode: '0600'

    - name: import public key
      shell: "gpg --import {{ public_key }}"

    - name: get fully qualified path of private key
      shell: "readlink -f {{ private_key }}"
      register: private_key_fq_path

    - name: import private key
      expect:
        command: "gpg --allow-secret-key-import --pinentry-mode loopback --import {{ private_key_fq_path.stdout }}"
        responses:
          (.*)passphrase(.*): "{{ gpg_passphrase }}"

    - name: clone to local password-store from remote
      git:
        repo: "{{ pass_repository }}"
        dest: "~/.password-store"
